name: screens_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.3.0
  path_provider_android: ^2.2.17
  path_provider: ^2.1.5
  shared_preferences_android: ^2.4.11
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/translations/
